### ISSUE TITLE
What is the "Update emojis" workflow for?

### ISSUE THREAD

**Issue by gr2m** [frontend-templates-world/new-snowpack-project#1]
Just curious about [`.github/workflows/update.yml`](https://github.com/frontend-templates-world/new-snowpack-project/blob/26c726ed1ad1147790112c50a86c6e28ec98c90a/.github/workflows/update.yml). Did you intend to add it or is that something you missed from a copy & paste?

**Comment by Olyno** [comment]
Ups, fixed 😅
