### ISSUE TITLE
Remove the "What port do you want to use?" question

### ISSUE THREAD

**Issue by gr2m** [frontend-templates-world/new-snowpack-project#4]
snowpack has a default built-in, and if if I recall correctly, it will try another port if `8080` is taken. See https://www.snowpack.dev/#config.devoptions

**Comment by Olyno** [comment]
I think we can change the default port (currently ``3000``) to ``8080`` but we should let the user be able to select the port he want when creating a new project

**Comment by gr2m** [comment]
As you like, I think I'd keep it simple and remove the question altogether

**Comment by Olyno** [comment]
Done in fb7bb23 ✅
