### ISSUE TITLE
rename package to `create-snowpack-app-interactive`

### ISSUE THREAD

**Issue by gr2m** [frontend-templates-world/new-snowpack-project#5]
That would work as a nice preview for what we are trying to do with https://github.com/snowpackjs/snowpack/issues/1277.

The `create-` prefix would allow use to create the new project with `npm init snowpack-app-interactive` / `yarn create snowpack-app-interactive`. Ideally we would be able to figure out whether `npm` or `yarn` was used and use that as default value for the "Which package manager should we use?" question

**Comment by Olyno** [comment]
Done ✅
