### ISSUE TITLE
seems like folder [randomfoldername] is not empty

### ISSUE THREAD

**Issue by shedali** [frontend-templates-world/new-snowpack-project#7]
Just testing

`pnpx create-snowpack-app-interactive` (version 0.2.0)

- chose svelte, with pnpm, no plugins

```
Downloading the selected template...Seems like "/Users/franz/dev/tmpsdflkjsdlfkjsdlfkjsdflkj" is not empty. Can't create the project there.
```

then hangs on Downloading the selected template...

**Comment by Olyno** [comment]
Seems like I put a wrong code line in this release, I fixed that
