### ISSUE TITLE
Cannot find module '@snowpack/plugin-build-script'

### ISSUE THREAD

**Issue by shedali** [frontend-templates-world/new-snowpack-project#9]
`npx create-snowpack-app-interactive test`
- use svelte
- use postcss
- use pnpm
`pnpm install` -> already up to date

`pnpm build`

`Error: Cannot find module '@snowpack/plugin-build-script'`

**Comment by Olyno** [comment]
Thanks you for your report, it has been fixed in the latest version 😃
